apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: frontend-svc
  name: frontend-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      run: frontend-svc
  template:
    metadata:
      labels:
        run: frontend-svc
    spec:
      containers:
      - image: vpstdacreu.azurecr.io/dotnet-daks-frontend:0.1
        name: frontend-svc
        ports:
        - containerPort: 9000
        command: ["dotnet", "GrpcFrontend.dll"]
        args: ["-f", "localhost", "-p", "9000", "-b", "10.110.11.142", "-t", "7000"]

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: frontend-svc
  name: frontend-svc
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: frontend-svc
  type: ClusterIP

